[package]
name = "wasmedge-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmedge-sdk = { path = "vendor/wasmedge-rust-sdk" }
tokio = { version = "1.35.1", features = ["full"] }
anyhow = "1.0"
futures = "0.3"
